name: Build
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.0

      - name: Create GitVersion.yml
        run: |
          cat <<EOF > GitVersion.yml
          major-version-bump-message: '(breaking|major|incompatible):'
          minor-version-bump-message: '(feature|minor|enhancement|new|update|improvement|upgrade|feat):'
          patch-version-bump-message: '(fix|patch|bugfix|hotfix|correction|adjustment|tweak):'
          no-bump-message: '(none|skip|no-release|trivial|docs|documentation|style|refactor|chore|test):'
          EOF

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.0.0
        with:
          useConfigFile: true

      - name: Push docker image release
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: cnieg/secret-certificat-azure-exporter:latest
