name: Build
on:
  push:
  pull_request:
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push docker image release
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: cnieg/secret-certificat-azure-exporter:latest
