name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Clippy
        run: cargo clippy --no-deps -- -Dwarnings

      - name: Run rustfmt
        run: cargo fmt --check

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.1

      - name: Create GitVersion.yml
        run: |
          cat <<EOF > GitVersion.yml
          major-version-bump-message: '(breaking|major|incompatible):'
          minor-version-bump-message: '(feature|minor|enhancement|new|update|improvement|upgrade|feat):'
          patch-version-bump-message: '(fix|patch|bugfix|hotfix|correction|adjustment|tweak):'
          no-bump-message: '(none|skip|no-release|trivial|docs|documentation|style|refactor|chore|test):'
          EOF

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.0.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image release
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: cnieg/secret-certificat-azure-exporter:${{ env.majorMinorPatch }}

      - name: Create tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ env.majorMinorPatch }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.20.0
        with:
          generateReleaseNotes: true
          tag: ${{ env.majorMinorPatch }}
